import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import  { Roboto_Mono } from "next/font/google"


const robot = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robot.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
