import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import  { Roboto_Mono } from "next/font/google"
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar";

const robot = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body
        className={`${robot.className}  antialiased`}
      >
        <SidebarProvider>
          <AppSidebar/>
          <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
            
                {children}
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
